def zarr_L1b_variables():
    return {
        "CalibrationErrors": {"long_name": "Error flags combined into single value (see documentation)", "units": "",
                              "dims": ("time", "im_row", "im_col")},
        "DataLevel": {"long_name": "Earth Observation Data Level", "units": "", "dims": ()},
        "ImageCalibrated": {"long_name": "Calibrated image (spectral radiance)",
                            "units": "photon nanometer-1 meter-2 steradian-1 second-1",
                            "dims": ("time", "im_row", "im_col")},
        "JPEGQ": {"long_name": "JPEG compression quality setting", "units": "", "dims": ()},
        "L1ACode": {"long_name": "Version and git commit hash of L1A software", "units": "", "dims": ()},
        "L1BCode": {"long_name": "Version and git commit hash of L1B software", "units": "", "dims": ()},
        "NCBINCCDColumns": {"long_name": "Number of columns binned together on-chip", "units": "", "dims": ()},
        "NCBINFPGAColumns": {"long_name": "Number of columns binned together in FPGA", "units": "", "dims": ()},
        "NCOL": {"long_name": "Number of columns in the image", "units": "", "dims": ()},
        "NCSKIP": {"long_name": "Number of columns skipped before binning", "units": "", "dims": ()},
        "NRBIN": {"long_name": "Number of rows that are binned together", "units": "", "dims": ()},
        "NROW": {"long_name": "Number of rows in the image", "units": "", "dims": ()},
        "NRSKIP": {"long_name": "Number of rows skipped before binning", "units": "", "dims": ()},
        "TEXPMS": {"long_name": "Image exposure duration", "units": "millisecond", "dims": ()},
        "TPheight": {"long_name": "Altitude of tangent point for nominal instrument axis at the time of measurement",
                     "units": "meter", "dims": ("time",)},
        "TPlat": {"long_name": "Latitude of tangent point for nominal instrument axis at the time of measurement",
                  "units": "degree_north", "dims": ("time",)},
        "TPlon": {"long_name": "Longitude of tangent point for nominal instrument axis at the time of measurement",
                  "units": "degree_east", "dims": ("time",)},
        "TPssa": {"long_name": "Solar scattering angle at tangent point", "units": "degree", "dims": ("time",)},
        "TPsza": {"long_name": "Solar zenith angle at tangent point", "units": "degree", "dims": ("time",)},
        # "WDWInputDataWindow": {"long_name": "Window configuration setting", "units": "", "dims": ("time",)},
        "afsAttitudeState": {"long_name": "Quaternion relating satelite body frame to Earth-centered inertial (ECI) coordinate",
                             "units": "", "dims": ("time", "quaternion")},
        "afsGnssStateJ2000": {"long_name": "GNSS state in J2000 frame", "units": "", "dims": ("time", "gnss_state")},
        "channel": {"long_name": "Channel name", "units": "", "dims": ()},
        "gnss_state": {"long_name": "GNSS State Components", "units": "", "dims": ("gnss_state",)},
        "im_col": {"long_name": "Image Column Number", "units": "", "dims": ("im_col",)},
        "im_row": {"long_name": "Image Row Number", "units": "", "dims": ("im_row",)},
        "nadir_az": {"long_name": "Solar azimuth angle at satellite position", "units": "degree", "dims": ("time",)},
        "nadir_sza": {"long_name": "Solar zenith angle at satellite position", "units": "degree", "dims": ("time",)},
        "qprime": {"long_name": "Quaternion relating channel to satellite body frame", "units": "",
                   "dims": ("time", "quaternion")},
        "quaternion": {"long_name": "Quaternion Components", "units": "", "dims": ("quaternion",)},
        "satheight": {"long_name": "Satellite altitude at time of measurement", "units": "meter", "dims": ("time",)},
        "satlat": {"long_name": "Satellite latitude at time of measurement", "units": "degree_north",
                   "dims": ("time",)},
        "satlon": {"long_name": "Satellite longitude at time of measurement", "units": "degree_east",
                   "dims": ("time",)},
        "schedule_id": {"long_name": "Schedule id", "units": "", "dims": ("time",)},
        "schedule_version": {"long_name": "Schedule version", "units": "", "dims": ("time",)},
        "schedule_yaw_correction": {"long_name": "Scheduled yaw correction (1 if True)", "units": "", "dims": ()},
        "temperature": {"long_name": "CCD housing temperature", "units": "degree_celsius", "dims": ("time",)},
        "time": {"long_name": "Time of Observation", "units": "nanoseconds since 2000-01-01", "dims": ("time",)},
        "TPheightPixel": {"long_name": "Altitude of tangent point for each pixel", "units": "meter",
                          "dims": ("time", "im_row", "im_col"), "skip": True},
        "TPECEFx": {"long_name": "Tangent point x coordinate in ECEF frame, for each pixel", "units": "meter",
                    "dims": ("time", "im_row", "im_col"), "skip": True},
        "TPECEFy": {"long_name": "Tangent point y coordinate in ECEF frame, for each pixel", "units": "meter",
                    "dims": ("time", "im_row", "im_col"), "skip": True},
        "TPECEFz": {"long_name": "Tangent point z coordinate in ECEF frame, for each pixel", "units": "meter",
                    "dims": ("time", "im_row", "im_col"), "skip": True},
    }
